server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url : jdbc:postgresql://eduwords-eng.cb20gsk0grwq.us-east-1.rds.amazonaws.com:5432/postgres;MODE=MySQL
    username : postgres
    password: postgres

    hikari:
      connection-timeout : 30000
      maximum-pool-size : 50
      minimum-idle : 30
      idle-timeout : 60000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    database : postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_jdbc_metadata_defaults: false
        format_sql: true

